# ReadTheDocs configuration file
# This file configures how ReadTheDocs builds your documentation

version: 2

# Build documentation in the environment specified by the requirements file
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation using pip
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation from the docs/ directory
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation in the docs/ directory
formats:
  - pdf
  - epub

# Additional build options
build_jobs: 2

# Environment variables
environment:
  PYTHONPATH: "."

# Submodules
submodules:
  include:
    - docs
