name: fracnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.2.0
  - scipy>=1.16.0
  - matplotlib>=3.10.0
  - pandas>=2.3.0
  - jax>=0.7.0
  - jaxlib>=0.7.0
  - numba>=0.61.0
  - sympy>=1.14.0
  - pytest>=8.4.0
  - pytest-benchmark>=5.1.0
  - pytest-cov>=6.2.0
  - sphinx>=8.2.0
  - sphinx-rtd-theme>=3.0.0
  - black>=25.1.0
  - flake8>=7.3.0
  - mypy>=1.17.0
  - pre-commit>=4.3.0
  - pip
  - pip:
    - hpfracc>=0.1.2
    - optax>=0.2.0
    - torch>=2.8.0
    - torchvision>=0.23.0
    - scikit-learn>=1.7.0
    - seaborn>=0.13.0
    - plotly>=6.3.0
    - joblib>=1.5.0
    - multiprocessing-logging>=0.3.0
    - psutil>=7.0.0
    - build>=1.0.0
    - twine>=4.0.0
