name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install numpyro>=0.13.0
      - name: Install package (editable)
        run: |
          pip install -e .
      - name: Run simple smoke test
        env:
          PYTHONPATH: ${{ github.workspace }}
          JAX_PLATFORM_NAME: cpu
        run: |
          bash scripts/smoke_test.sh
